<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <head>
    <title>SuccessWhale</title>
	<link rel="shortcut icon" href="favicon.ico">
	<link type="text/css" rel="stylesheet" media="all" href="default.css" />
	<link type="text/css" rel="stylesheet" media="all" href="<?php echo($_COOKIE['theme']) ?>" />
	<!--[if lt IE 7]>
      	<link type="text/css" rel="stylesheet" media="all" href="ie/ie.css" />
      <![endif]-->
	<script type="text/javascript" src="jquery.min.js"></script>
	<script type="text/javascript" src="jquery.form.js"></script>
	<script type="text/javascript" src="jquery.blockUI.js"></script>

  </head>
  <body>
	<SCRIPT LANGUAGE="JavaScript" SRC="javascript.js"></SCRIPT>
	
	<?php echo($content); ?>
	
	
    <SCRIPT LANGUAGE="JavaScript">
    // Trigger init
    window.onload=init();
    </SCRIPT>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-8537137-2");
pageTracker._trackPageview();
} catch(err) {}</script>

</body></html>
